# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jul  4 12:04:50 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 600)
        MainWindow.setMinimumSize(QtCore.QSize(880, 600))
        MainWindow.setMaximumSize(QtCore.QSize(880, 600))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 861, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search = QtGui.QLineEdit(self.horizontalLayoutWidget_2)
        self.search.setMinimumSize(QtCore.QSize(450, 25))
        self.search.setMaximumSize(QtCore.QSize(450, 25))
        self.search.setText("")
        self.search.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.search.setObjectName("search")
        self.horizontalLayout_2.addWidget(self.search)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label.setMinimumSize(QtCore.QSize(180, 25))
        self.label.setMaximumSize(QtCore.QSize(180, 25))
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.searchBox = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.searchBox.setMinimumSize(QtCore.QSize(200, 0))
        self.searchBox.setMaximumSize(QtCore.QSize(200, 25))
        self.searchBox.setObjectName("searchBox")
        self.horizontalLayout_2.addWidget(self.searchBox)
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 40, 861, 502))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableView = QtGui.QTableView(self.horizontalLayoutWidget_3)
        self.tableView.setMinimumSize(QtCore.QSize(500, 500))
        self.tableView.setMaximumSize(QtCore.QSize(500, 500))
        self.tableView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_3.addWidget(self.tableView)
        self.showInfo = QtGui.QWidget(self.horizontalLayoutWidget_3)
        self.showInfo.setMinimumSize(QtCore.QSize(350, 0))
        self.showInfo.setMaximumSize(QtCore.QSize(350, 460))
        self.showInfo.setObjectName("showInfo")
        self.label_2 = QtGui.QLabel(self.showInfo)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.showInfo)
        self.label_3.setGeometry(QtCore.QRect(10, 30, 131, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.showInfo)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 41, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.showInfo)
        self.label_5.setGeometry(QtCore.QRect(10, 70, 51, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.common = QtGui.QLabel(self.showInfo)
        self.common.setGeometry(QtCore.QRect(130, 10, 221, 16))
        self.common.setText("")
        self.common.setObjectName("common")
        self.cientific = QtGui.QLabel(self.showInfo)
        self.cientific.setGeometry(QtCore.QRect(140, 30, 211, 16))
        self.cientific.setText("")
        self.cientific.setObjectName("cientific")
        self.type = QtGui.QLabel(self.showInfo)
        self.type.setGeometry(QtCore.QRect(50, 50, 301, 16))
        self.type.setText("")
        self.type.setObjectName("type")
        self.data = QtGui.QLabel(self.showInfo)
        self.data.setGeometry(QtCore.QRect(20, 90, 321, 101))
        self.data.setText("")
        self.data.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.data.setObjectName("data")
        self.graphicsView = QtGui.QGraphicsView(self.showInfo)
        self.graphicsView.setGeometry(QtCore.QRect(10, 200, 331, 251))
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_3.addWidget(self.showInfo)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 25))
        self.menubar.setObjectName("menubar")
        self.menuOpciones = QtGui.QMenu(self.menubar)
        self.menuOpciones.setObjectName("menuOpciones")
        self.AboutUs = QtGui.QMenu(self.menubar)
        self.AboutUs.setObjectName("AboutUs")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.add = QtGui.QAction(MainWindow)
        self.add.setObjectName("add")
        self.edit = QtGui.QAction(MainWindow)
        self.edit.setObjectName("edit")
        self.btn_delete = QtGui.QAction(MainWindow)
        self.btn_delete.setObjectName("btn_delete")
        self.quit = QtGui.QAction(MainWindow)
        self.quit.setObjectName("quit")
        self.actionAcerca_de = QtGui.QAction(MainWindow)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionVer_Leeme = QtGui.QAction(MainWindow)
        self.actionVer_Leeme.setObjectName("actionVer_Leeme")
        self.menuOpciones.addAction(self.add)
        self.menuOpciones.addAction(self.edit)
        self.menuOpciones.addAction(self.btn_delete)
        self.menuOpciones.addSeparator()
        self.menuOpciones.addAction(self.quit)
        self.AboutUs.addAction(self.actionVer_Leeme)
        self.AboutUs.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuOpciones.menuAction())
        self.menubar.addAction(self.AboutUs.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Animales", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Buscar animal", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Buscar por tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Nombre común:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Nombre científico:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Tipo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Datos:", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOpciones.setTitle(QtGui.QApplication.translate("MainWindow", "Archivo", None, QtGui.QApplication.UnicodeUTF8))
        self.AboutUs.setTitle(QtGui.QApplication.translate("MainWindow", "Ayuda", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setText(QtGui.QApplication.translate("MainWindow", "Nuevo animal", None, QtGui.QApplication.UnicodeUTF8))
        self.add.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.edit.setText(QtGui.QApplication.translate("MainWindow", "Editar animal", None, QtGui.QApplication.UnicodeUTF8))
        self.edit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete.setText(QtGui.QApplication.translate("MainWindow", "Eliminar animal", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_delete.setShortcut(QtGui.QApplication.translate("MainWindow", "Del", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setText(QtGui.QApplication.translate("MainWindow", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.quit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("MainWindow", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setShortcut(QtGui.QApplication.translate("MainWindow", "F2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVer_Leeme.setText(QtGui.QApplication.translate("MainWindow", "Ver Leeme", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVer_Leeme.setShortcut(QtGui.QApplication.translate("MainWindow", "F1", None, QtGui.QApplication.UnicodeUTF8))
